name: Continuous Integration

on:
  workflow_call:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v7

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build the Application
        run: mvn -B clean verify